config/routes.rb
Rails.application.routes.draw do

  resources :people
	get "/welcome/say_hello" => "welcome#say"

	get "welcome" => "welcome#index"

	root 'welcome#index'

	match ':controller(/:action(/:id(.:format)))', :via => :all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
	validates_presence_of :name
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	before_action :set_event, :only => [:show, :edit, :update, :destroy]

	def index
		@events = Event.page(params[:page]).per(10)
	end

	def new
		@event = Event.new
	end

	#post/ events/ create
	def create
		@event = Event.new(event_parms)
		if @event.save
			flash[:notice] = "新增成功"
			redirect_to :action => :index #告訴瀏覽器 HTTP code: 303
		else
			render :action => :new #new.html.erb
		end
	end




	#show data detail
	def show
		@title = @event.name
	end
    
    #get /events/edit/:id
	def edit
	end

	#get /events/update/:id
	def update
		@event.update(event_parms)
		if @event.update(event_parms)
			flash[:notice] = "編輯成功"
			redirect_to :action => :show, :id => @event
		else
			render :action => :edit
		end
	end

	def destroy 
		@event.destroy
		flash[:alert] = "刪除成功"
		redirect_to :action => :index #告訴瀏覽器 HTTP code: 303
	end

	#為了簡潔而寫的before_action fuction
	def set_event
		@event = Event.find(params[:id])
	end




	private
		def event_parms
			params.require(:event).permit(:name, :description)
		end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :bio, :birthday)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	# Get/welcome/say_hello
	def say
		# view/welcome/say.html.erb
	end
	
	def index 
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<p>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>
</p>
<p>
    <%= f.label :description, "Description" %>
    <%= f.text_area :description %>
</p>

<% if @event.errors.any? %>
      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
<% end %>

app/views/events/edit.html.erb
<%= form_for @event, :url => { :controller => 'events', :action => 'update', :id => @event } do |f| %>
   
   <%= render :partial => "form", :locals => {:f => f} %>

    <%= f.submit "Update" %>
<% end %>

app/views/events/index.html.erb
<h1>Events list</h1>

<p style="color: green"><%= flash[:notice] %></p>
<p style="color: red"><%= flash[:alert] %></p>

<ul>
	<% @events.each do |e| %>

	<li>
		<%= e.name %> 
		<%= link_to "Show", :controller => "events", :action => "show", :id => e %>
		<%= link_to "Edit", :controller => "events", :action => "edit", :id => e %>
		<%= link_to "Delete", :controller => "events", :action => "destroy", :id => e %>
	</li>

<% end %>
</ul>

<%= link_to 'Button Go', :controller => 'events', :action => 'new'%>

app/views/events/new.html.erb
<%= form_for @event, :url => { :controller => 'events', :action => 'create' } do |f| %>

    <%= render :partial => "form", :locals => {:f => f} %>

    <%= f.submit "Create" %>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>
<%= simple_format @event.description %>

<p><%= link_to '上一頁', :controller => 'events', :action => 'index' %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title || "Demo" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <p>
    <%= paginate @events %>
    </p>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_for(person) do |f| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :bio %>
    <%= f.text_area :bio %>
  </div>

  <div class="field">
    <%= f.label :birthday %>
    <%= f.date_select :birthday %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bio</th>
      <th>Birthday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.bio %></td>
        <td><%= person.birthday %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @person.bio %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @person.birthday %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/welcome/index.html.erb
<p>Hola! It's <%= Time.now %></p>
<p><%= link_to 'Hello!', welcome_say_hello_path %></p>

app/views/welcome/say.html.erb
<h1>Hello, World!!</h1>
<%= link_to 'data page', :controller => 'events', :action => 'index'%>